### PR TITLE
F site layout

### PR DESCRIPTION
**Pull request by andrewgriflan**

### CODE REVIEW

**Comment by davidpanzarella** [comment]
@andrewgriflan Can you pull in the latest changes, and fix these conflicts before doing another PR? I updated the Gulp file quite a bit, as well as paths for all images and such to live in the `dist/` with the other compressed files. I also combined all of the css & js so that we can speed the load time a bit. If you have any questions, let me know.

**Comment by andrewgriflan** [comment]
@davidpanzarella I have merged master and fixed conflicts in favor of my changes (due to the binary issue we have discussed). If you make a patch file of your changes id be happy to update this for you. Thanks!

**Comment by davidpanzarella** [comment]
@andrewgriflan I was going to work on this today. Did you bring in master in its current form, and just update your changes on top? Eg. did you change gulp back to what it was, etc

**Comment by andrewgriflan** [comment]
I believe the only thing that wasnt merged correctly was the index file. Everything else should be merged properly. I did update the img URL's to point to the new location of the image directory

**Pull request merged**
